---
- name: Validate complete SSH configuration
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Reload SSH

- name: Reload SSH service
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Reload SSH
