---
- name: Verify the workspace platform
  ansible.builtin.import_tasks: platform.yml

- name: Install required workspace packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure automatic security updates
  ansible.builtin.import_tasks: updates.yml

- name: Manage workspace accounts
  ansible.builtin.import_tasks: users.yml
