---
- name: Create Rivet service group
  ansible.builtin.group:
    name: rivet
    system: true
    state: present

- name: Create Rivet service account
  ansible.builtin.user:
    name: rivet
    comment: Rivet service account
    group: rivet
    groups: ""
    home: /home/rivet
    shell: /bin/bash
    create_home: true
    system: true
    password_lock: true
    state: present

- name: Maintain Rivet administrative account
  ansible.builtin.user:
    name: rivet-admin
    comment: Rivet administrator
    groups:
      - adm
      - sudo
    append: false
    home: /home/rivet-admin
    shell: /bin/bash
    create_home: true
    password_lock: true
    state: present

- name: Maintain passwordless administrative access
  ansible.builtin.copy:
    content: |
      rivet-admin ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/rivet-admin
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
