all:
  children:
    rivet_workspace:
      hosts:
        rivet-workspace:
          ansible_host: "{{ lookup('ansible.builtin.env', 'RIVET_WORKSPACE_IP', default=undef()) }}"
          ansible_user: rivet-admin
          rivet_operator_ipv4_cidr: "{{ lookup('ansible.builtin.env', 'RIVET_OPERATOR_IPV4_CIDR', default=undef()) }}"
