all:
  children:
    rivet_workspace:
      hosts:
        rivet-workspace:
          ansible_host: "{{ lookup('ansible.builtin.env', 'RIVET_WORKSPACE_IP', default=undef()) }}"
          ansible_user: rivet-admin
